In [1]:
# pip install torch==2.0.1

In [2]:
import torch

torch.__version__

'2.0.1+cu117'

In [3]:
torch.cuda.is_available()

False

In [5]:
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1, 2, 3])

tensor2d = torch.tensor([[1, 2], [3, 4]])

tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [9]:
print(tensor0d)

print(tensor1d)

print(tensor2d)

print(tensor3d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [10]:
print(tensor1d.dtype)

torch.int64


In [11]:
# float tensor
tensor_float = torch.tensor([1.0, 2.0, 3.0])
print(tensor_float.dtype)

torch.float32


- 32-bit floating point number offers sufficient precision for most deep learning tasks, while consuming less memory and computational resources than a 64-bit
- GPU architectures are optimized for 32-bit computations

In [14]:
tensor_change_float = tensor1d.to(torch.float32)
print(tensor_change_float.dtype)

torch.float32


In [15]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor2d.shape)

torch.Size([2, 3])


In [16]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [18]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [19]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [20]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [21]:
# we can also adopt the @ operator
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])
